### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dan-klasson** [vitaly/dotvim2#2]
So I clone this repo. Go into the dotvim2 folder and run `make`, answer all the prompts and then it says `DONE`. But when I open Vim, none of the plugins work, nor is the leader key `,`. 

What am I missing in my install?

**Comment by vitaly** [comment]
You missing reading the README ;)

But you are right of course, this is probably not very clear. by default it generates the config in the `./dist` directory. You can override it with `VIM_DIR=~/.vim make`

You are probably not the only one stumbled on this, so I'll try to work something out to fix it.

**Comment by vitaly** [comment]
latest version will check for non-standard VIM_DIR location and print a warning

**Comment by dan-klasson** [comment]
Sure it generates the files in the `./dist` directory. But how do we get it working?

Running `VIM_DIR=~/.vim make` in the root rolder gives me `make: *** No targets specified and no makefile found.  Stop.`. Running the same in the `dotvim2` folder gives me the same as explained above. 

Please clarify the steps to get it up and running.

**Comment by cescue** [comment]
Vim probably isn't using the configuration file you're expecting it to.  The one that is being generated lives in `VIM_DIR/vimrc`.  You should be able to fix this in one of two ways:

1.  Copy the generated `vimrc` file to the filename expected by vim (this is typically `~/.vimrc`.
2.  Explicitly tell vim to use the generated config file:  `vim -u VIM_DIR/vimrc`

**Comment by vitaly** [comment]
@cescue @dan-klasson indeed, older versions of vim will only look for `~/.vimrc`. Newer versions also look directly for `~/.vim/vimrc`. I'll add that to the readme and installation warning.

**Comment by vitaly** [comment]
done.
