### ISSUE TITLE
Dein requesting ENTER every time

### ISSUE THREAD

**Issue by ramonpm** [vitaly/dotvim2#6]
Every time I open a file it shows me this lines:

[dein] (1/5) [====                ] Merginal
[dein] (2/5) [========            ] apidock.vim
[dein] (3/5) [============        ] YankRing.vim
[dein] (4/5) [================    ] greplace.vim
[dein] (5/5) [====================] utl.vim
[dein] Done: (2017/08/18 09:11:03)Press ENTER or type command to continue

So, every time I need to press ENTER to continue, that's annoying hehehe

Could you help me solve this?

**Comment by borod108** [comment]
For me https://github.com/vitaly/dotvim2/pull/7 solved it.

**Comment by borod108** [comment]
Try to go to: .vim/vimrc.plugins
and add 'vim-scripts' to all teh dein calls for those plugins, for example:
change: `call dein#add('utl.vim')`
to: `call dein#add('vim-scripts/utl.vim')`
It will update them next time you open it and then it wont update them again, at least it worked for me.

**Comment by vitaly** [comment]
does it still happen?

**Comment by ramonpm** [comment]
Not sure, I've not using it anymore.
